schemaVersion: 2.3.0
metadata:
  name: redhat-chat
  displayName: Red Hat Chat
  description: Red Hat Chat - Tech Preview with LibreChat and Red Hat Design System
  tags:
    - nodejs
    - chat
    - ai
    - redhat
  projectType: nodejs
  language: typescript
  version: 0.8.1-rc2
  attributes:
    tech-preview: "true"
components:
  # Main container for both OpenShift CLI and Node.js tasks
  # Uses base developer image (includes oc, kubectl) - Node.js will be installed via init-workspace-full
  - name: api
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      memoryLimit: 4Gi
      cpuLimit: 2000m
      cpuRequest: 500m
      endpoints:
        - name: http
          targetPort: 3080
          exposure: public
          protocol: http
          path: /
        - name: api-internal
          targetPort: 3080
          exposure: none
          protocol: http
          path: /
      env:
        - name: NODE_ENV
          value: development
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "3080"
        - name: DOMAIN
          value: http://localhost:3080
        - name: MONGO_URI
          value: mongodb://127.0.0.1:27017/LibreChat
        - name: SEARCH
          value: "false"
        # RAG API is optional - uncomment vectordb and rag-api components to enable
        # - name: RAG_API_URL
        #   value: http://rag-api:8000
        # - name: RAG_PORT
        #   value: "8000"
        # JWT Secrets - generate secure values for production
        - name: JWT_SECRET
          value: 8a447c316c171f5df8e304c085187b6d10e4eeef5174137d4ad4d2cdd956f5e7
        - name: JWT_REFRESH_SECRET
          value: 83096493d70e22561f84191c24f459d72e9b41f4c8657fe43aae8cb9b0fe1fa4
        - name: JWT_EXPIRES_IN
          value: 1d
        - name: JWT_REFRESH_EXPIRES_IN
          value: 7d
        # Authentication settings
        - name: ALLOW_EMAIL_LOGIN
          value: "true"
        - name: ALLOW_REGISTRATION
          value: "true"
        - name: ALLOW_SOCIAL_LOGIN
          value: "true"
        # Development mode settings
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: "debug"
        # OpenID/OAuth configuration (optional - uncomment and configure if needed)
        # - name: OPENID_LOGIN_ENABLED
        #   value: "true"
        # - name: OPENID_ISSUER
        #   value: https://auth.redhat.com/realms/librechat
        # - name: OPENID_CLIENT_ID
        #   value: client-id
        # - name: OPENID_CLIENT_SECRET
        #   value: client-secret
        # - name: OPENID_SCOPE
        #   value: openid profile email
        # Embeddings (without Ollama - use OpenAI or disable)
        # - name: EMBEDDINGS_PROVIDER
        #   value: openai
        # - name: OPENAI_API_KEY
        #   value: sk-your_openai_api_key_here
      volumeMounts:
        - name: images-data
          path: /app/client/public/images
        - name: uploads-data
          path: /app/uploads
        - name: logs-data
          path: /app/api/logs
      sourceMapping: /
      command:
        - sleep
        - infinity
  # nodejs component - let parent handle it completely, we don't override
  # The parent will provide Node.js configuration
  - name: mongodb
    container:
      image: docker.io/library/mongo:7.0
      memoryLimit: 512Mi
      endpoints:
        - name: mongodb
          targetPort: 27017
          exposure: internal
          protocol: tcp
      command:
        - mongod
        - --noauth
        - --bind_ip_all
      volumeMounts:
        - name: mongodb-data
          path: /data/db
  # Ollama component - commented out due to resource constraints
  # Uncomment when you have sufficient resources (4Gi+ memory available)
  #- name: ollama
  #  attributes:
  #    container-overrides:
  #      resources:
  #        limits:
  #          cpu: 2000m
  #          memory: 4Gi
  #          # nvidia.com/gpu: 1 # Uncomment this if the pod shall be scheduled only on a GPU node
  #        requests:
  #          cpu: 500m
  #          memory: 2Gi
  #          # nvidia.com/gpu: 1 # Uncomment this if the pod shall be scheduled only on a GPU node
  #  container:
  #    image: docker.io/ollama/ollama:latest
  #    mountSources: true
  #    sourceMapping: /.ollama
  #    endpoints:
  #      - name: ollama
  #        targetPort: 11434
  #        exposure: internal
  #        protocol: http
  #        path: /
  # VectorDB (pgvector) - Required for RAG API functionality
  # Note: VectorDB may have issues in some OpenShift environments
  #- name: vectordb
  #  container:
  #    image: docker.io/pgvector/pgvector:0.8.0-pg15-trixie
  #    memoryLimit: 1Gi
  #    cpuLimit: 500m
  #    endpoints:
  #      - name: postgres
  #        targetPort: 5432
  #        exposure: none
  #        protocol: tcp
  #    env:
  #      - name: POSTGRES_DB
  #        value: mydatabase
  #      - name: POSTGRES_USER
  #        value: myuser
  #      - name: POSTGRES_PASSWORD
  #        value: mypassword
  #    volumeMounts:
  #      - name: pg-data
  #        path: /var/lib/postgresql/data
  # - name: rag-api
  #   container:
  #     image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
  #     memoryLimit: 1Gi
  #     endpoints:
  #       - name: rag-api
  #         targetPort: 8000
  #         exposure: none
  #         protocol: http
  #     env:
  #       - name: DB_HOST
  #         value: vectordb
  #       - name: RAG_PORT
  #         value: "8000"
  #       - name: OPENAI_API_KEY
  #         value: ""
  - name: images-data
    volume:
      size: 1Gi
  - name: uploads-data
    volume:
      size: 1Gi
  - name: logs-data
    volume:
      size: 500Mi
  - name: mongodb-data
    volume:
      size: 2Gi
  # pg-data volume for vectordb
  - name: pg-data
    volume:
      size: 1Gi
commands:
  # Custom Node.js tasks - using different names to avoid conflicts with parent
  - id: init-custom
    exec:
      component: api
      commandLine: |
        echo "Initializing Red Hat Chat workspace..."
        # Ensure Node.js is available
        if ! command -v node &> /dev/null; then
          echo "Node.js not found. Please run 'devfile init-workspace-full' first to install Node.js"
          exit 1
        fi
        npm install
  - id: build-custom
    exec:
      component: api
      commandLine: |
        cd /projects/librechat-redhat || cd /projects || pwd
        echo "Building for production..."
        npm install --legacy-peer-deps --workspaces || npm install --legacy-peer-deps || npm install
        echo "Building packages..."
        npm run build:packages
        echo "Building client (production)..."
        npm run build:client
  - id: build-dev
    exec:
      component: api
      commandLine: |
        cd /projects/librechat-redhat || cd /projects || pwd
        echo "Building packages for DEV mode..."
        npm install --legacy-peer-deps --workspaces || true
        npm run build:packages
        echo "✓ Packages built (client uses dev server, no build needed)"
  - id: run-backend
    exec:
      component: api
      commandLine: |
        cd /projects/librechat-redhat || cd /projects || pwd
        # Ensure Node.js is available
        if ! command -v node &> /dev/null; then
          echo "Node.js not found. Please run 'devfile init-workspace-full' first to install Node.js"
          exit 1
        fi
        
        # Quick wait for MongoDB (reduced attempts for dev mode)
        echo "Waiting for MongoDB..."
        MAX_ATTEMPTS=15
        ATTEMPT=0
        while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
          if (command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 27017 2>/dev/null) || \
             (command -v timeout >/dev/null 2>&1 && timeout 1 bash -c "echo > /dev/tcp/127.0.0.1/27017" 2>/dev/null) || \
             (command -v mongosh >/dev/null 2>&1 && mongosh --host 127.0.0.1 --port 27017 --eval "db.adminCommand('ping')" --quiet >/dev/null 2>&1); then
            echo "✓ MongoDB ready"
            break
          fi
          ATTEMPT=$((ATTEMPT + 1))
          [ $((ATTEMPT % 5)) -eq 0 ] && echo "  Waiting for MongoDB... ($ATTEMPT/$MAX_ATTEMPTS)"
          sleep 1
        done
        
        # Quick dependency check (only if missing)
        if [ ! -d node_modules ] || [ ! -f node_modules/.bin/cross-env ]; then
          echo "Installing dependencies..."
          npm install --legacy-peer-deps --workspaces || npm install --legacy-peer-deps || npm install
        fi
        
        # Create .env if missing
        if [ ! -f .env ] && [ -f env.example.podman ]; then
          cp env.example.podman .env
          echo "✓ .env created from env.example.podman"
        fi
        
        # Build packages only if missing (required for backend)
        if [ ! -f packages/data-schemas/dist/index.cjs ] || [ ! -f packages/data-provider/dist/index.cjs ]; then
          echo "Building packages..."
          npm run build:packages || echo "⚠ Package build failed, continuing anyway..."
        fi
        
        # In dev mode, skip client build - use dev server instead
        echo "Starting backend in DEV mode (client will use dev server)..."
        npm run backend:dev
  - id: start-backend
    exec:
      component: api
      commandLine: |
        cd /projects/librechat-redhat || cd /projects || pwd
        if ! command -v node &> /dev/null; then
          echo "Node.js not found. Run 'devfile init-workspace-full' first"
          exit 1
        fi
        # Quick start - minimal checks for dev mode
        [ ! -d node_modules ] && npm install --legacy-peer-deps --workspaces || true
        [ ! -f packages/data-schemas/dist/index.cjs ] && npm run build:packages || true
        npm run backend:dev
  - id: start-frontend
    exec:
      component: api
      commandLine: |
        cd /projects/librechat-redhat || cd /projects || pwd
        if ! command -v node &> /dev/null; then
          echo "Node.js not found. Run 'devfile init-workspace-full' first"
          exit 1
        fi
        echo "Starting frontend dev server..."
        npm run frontend:dev
  - id: init-workspace
    exec:
      component: api
      commandLine: |
        echo "Red Hat Chat - DEV Mode Ready" || true
        echo "Run: devfile init-workspace-full" || true
        echo "Then: devfile run-backend" || true
  - id: init-workspace-full
    exec:
      component: api
      commandLine: |
        echo "Initializing workspace for DEV mode..."
        cd /projects/librechat-redhat || cd /projects || pwd
        
        # Install Node.js if not available (simplified for dev)
        if ! command -v node &> /dev/null; then
          echo "Installing Node.js 20..."
          export NVM_DIR="$HOME/.nvm"
          if ! command -v nvm &> /dev/null; then
            mkdir -p "$NVM_DIR"
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          fi
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          if command -v nvm &> /dev/null; then
            nvm install 20 && nvm use 20 && nvm alias default 20
            echo "✓ Node.js installed"
          elif command -v dnf &> /dev/null && dnf install -y nodejs npm 2>/dev/null; then
            echo "✓ Node.js installed via dnf"
          else
            echo "⚠ Node.js installation failed. Please install manually."
            exit 1
          fi
        fi
        
        if ! command -v node &> /dev/null; then
          echo "✗ Node.js not available"
          exit 1
        fi
        
        echo "✓ Node.js: $(node -v), npm: $(npm -v)"
        
        # Install dependencies (simplified for dev)
        if [ -f package.json ]; then
          echo "Installing dependencies..."
          npm install --legacy-peer-deps --workspaces || npm install --legacy-peer-deps || npm install || echo "⚠ Some install issues, continuing..."
          
          # Build packages (required for backend)
          echo "Building packages..."
          npm run build:packages || echo "⚠ Package build issues, you can retry later"
        fi
        
        # Create config files if missing
        [ ! -f .env ] && [ -f env.example.podman ] && cp env.example.podman .env && echo "✓ .env created"
        [ ! -f librechat.yaml ] && [ -f librechat.example.yaml ] && cp librechat.example.yaml librechat.yaml && echo "✓ librechat.yaml created"
        
        echo "✓ Workspace ready for DEV mode"
        echo "Run 'devfile run-backend' to start backend"
        echo "Run 'devfile start-frontend' to start frontend dev server"
  - id: deploy-setup
    exec:
      component: api
      commandLine: |
        # Use current project/namespace from workspace, or fallback to OPENSHIFT_NAMESPACE
        NAMESPACE=$(oc project -q 2>/dev/null || echo "${OPENSHIFT_NAMESPACE:-maximilianopizarro5-dev}")
        if [ -z "$NAMESPACE" ] || [ "$NAMESPACE" = "default" ]; then
          NAMESPACE=${OPENSHIFT_NAMESPACE:-maximilianopizarro5-dev}
        fi
        echo "Setting up deployment for namespace: $NAMESPACE"
        # Ensure we're in the correct namespace
        oc project $NAMESPACE 2>/dev/null || oc create namespace $NAMESPACE
        if ! oc get secret redhat-chat-secrets -n $NAMESPACE &> /dev/null; then
          JWT_SECRET=$(openssl rand -hex 32)
          JWT_REFRESH_SECRET=$(openssl rand -hex 32)
          oc create secret generic redhat-chat-secrets \
            --from-literal=jwt-secret=$JWT_SECRET \
            --from-literal=jwt-refresh-secret=$JWT_REFRESH_SECRET \
            -n $NAMESPACE
          echo "✓ Secrets created"
        else
          echo "✓ Secrets already exist"
        fi
        cd manifests/base && oc apply -k . -n $NAMESPACE && cd ../..
        echo "✓ Base manifests applied"
        oc apply -f .tekton/pipeline.yaml -n $NAMESPACE
        echo "✓ Pipeline created"
  - id: deploy-run
    exec:
      component: api
      commandLine: |
        # Use current project/namespace from workspace
        NAMESPACE=$(oc project -q 2>/dev/null || echo "${OPENSHIFT_NAMESPACE:-maximilianopizarro5-dev}")
        if [ -z "$NAMESPACE" ] || [ "$NAMESPACE" = "default" ]; then
          NAMESPACE=${OPENSHIFT_NAMESPACE:-maximilianopizarro5-dev}
        fi
        PIPELINE_RUN_NAME="redhat-chat-pipeline-run-$(date +%s)"
        cat <<EOF | oc apply -f -
        apiVersion: tekton.dev/v1beta1
        kind: PipelineRun
        metadata:
          name: $PIPELINE_RUN_NAME
          namespace: $NAMESPACE
        spec:
          pipelineRef:
            name: redhat-chat-pipeline
          params:
            - name: git-url
              value: https://github.com/maximilianoPizarro/LibreChat-RedHat
            - name: git-revision
              value: main
            - name: image-name
              value: redhat-chat
            - name: image-tag
              value: latest
            - name: namespace
              value: $NAMESPACE
            - name: quay-repository
              value: maximilianopizarro/redhat-chat
          workspaces:
            - name: source
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi
        EOF
        echo "✓ PipelineRun $PIPELINE_RUN_NAME created"
        echo "Monitor with: oc get pipelineruns -n $NAMESPACE -w"
        echo "View logs: oc logs -f pipelinerun/$PIPELINE_RUN_NAME -n $NAMESPACE"
  - id: deploy-expose
    exec:
      component: api
      commandLine: |
        # Use current project/namespace from workspace
        NAMESPACE=$(oc project -q 2>/dev/null || echo "${OPENSHIFT_NAMESPACE:-maximilianopizarro5-dev}")
        if [ -z "$NAMESPACE" ] || [ "$NAMESPACE" = "default" ]; then
          NAMESPACE=${OPENSHIFT_NAMESPACE:-maximilianopizarro5-dev}
        fi
        if ! oc get route redhat-chat -n $NAMESPACE &> /dev/null; then
          oc expose service redhat-chat -n $NAMESPACE
          echo "✓ Route created"
        else
          echo "✓ Route already exists"
        fi
        oc get route redhat-chat -n $NAMESPACE
  - id: deploy-status
    exec:
      component: api
      commandLine: |
        # Use current project/namespace from workspace
        NAMESPACE=$(oc project -q 2>/dev/null || echo "${OPENSHIFT_NAMESPACE:-maximilianopizarro5-dev}")
        if [ -z "$NAMESPACE" ] || [ "$NAMESPACE" = "default" ]; then
          NAMESPACE=${OPENSHIFT_NAMESPACE:-maximilianopizarro5-dev}
        fi
        echo "=== Deployment Status ==="
        oc get deployment redhat-chat -n $NAMESPACE
        echo ""
        echo "=== Pods ==="
        oc get pods -n $NAMESPACE -l app=redhat-chat
        echo ""
        echo "=== Route ==="
        oc get route redhat-chat -n $NAMESPACE 2>/dev/null || echo "Route not found"
        echo ""
        echo "=== PipelineRuns ==="
        oc get pipelineruns -n $NAMESPACE
  # Ollama model download commands - commented out due to resource constraints
  # Uncomment when Ollama component is enabled
  #- id: pull-ollama-model
  #  exec:
  #    component: ollama
  #    commandLine: |
  #      echo "Waiting for Ollama to be ready..."
  #      MAX_ATTEMPTS=30
  #      ATTEMPT=0
  #      while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
  #        if curl -s http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then
  #          echo "✓ Ollama is ready"
  #          break
  #        fi
  #        ATTEMPT=$((ATTEMPT + 1))
  #        if [ $((ATTEMPT % 5)) -eq 0 ]; then
  #          echo "  Attempt $ATTEMPT/$MAX_ATTEMPTS: Ollama not ready yet, waiting..."
  #        fi
  #        sleep 2
  #      done
  #      if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
  #        echo "⚠ Warning: Ollama may not be ready, but attempting to pull model anyway..."
  #      fi
  #      echo "Pulling model llama3.2:3b-instruct-q4_K_M..."
  #      ollama pull llama3.2:3b-instruct-q4_K_M || {
  #        echo "⚠ Failed to pull model, will retry later. You can manually pull it with: ollama pull llama3.2:3b-instruct-q4_K_M"
  #        exit 0  # Don't fail the hook, allow workspace to start
  #      }
  #      echo "✓ Model pulled successfully"
  #- id: pull-autocomplete-model
  #  exec:
  #    component: ollama
  #    commandLine: |
  #      echo "Pulling autocomplete model starcoder2:3b..."
  #      ollama pull starcoder2:3b || {
  #        echo "⚠ Failed to pull autocomplete model, will retry later. You can manually pull it with: ollama pull starcoder2:3b"
  #        exit 0  # Don't fail the hook, allow workspace to start
  #      }
  #      echo "✓ Autocomplete model pulled successfully"
  - id: copy-continue-config
    exec:
      component: api
      commandLine: |
        [ -f continue-config.json ] && mkdir -p /home/user/.continue && cp continue-config.json /home/user/.continue/config.json 2>/dev/null || true
events:
  postStart:
    - copy-continue-config
