source "https://rubygems.org"

# Jekyll
gem "jekyll", "~> 4.3"

# Plugins
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.4"

# Markdown
gem "kramdown", "~> 2.4"
gem "kramdown-parser-gfm", "~> 1.1"

# Syntax highlighting
gem "rouge", "~> 4.2"

# Windows support
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Performance
gem "jekyll-minifier", "~> 0.1.10"

